version: "2"

services:

  postgis:
    image: thinkwhere/postgis:geopy
    environment:
      - POSTGRES_USER=geopython
      - POSTGRES_PASSWORD=geopython
      - POSTGRES_DB=geopython-db
    ports:
      - "5432:5432"

  rabbitmq:
    # Message broker for Celery
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=celery_user
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_VHOST=celery_app
    ports:
      # The rabbitMQ management plugin - running on http://localhost:15672
      - "15672:15672"
      - "5672:5672"

  celery:
    # Python application which run the Celery worker
    build:
      context: celery_app
      dockerfile: docker/celery.dockerfile
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - postgis

  flower:
    # Monitoring application - running on http://localhost:5555
    build:
      context: celery_app
      dockerfile: docker/flower.dockerfile
    links:
      - celery
      - rabbitmq
    depends_on:
      - celery
    ports:
      - "5555:5555"
